// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdO-LjFNK3TDE0C0UfivNCe4_Xs-CVGj8',
    appId: '1:74105196603:web:0f7d19c56f42229d4e0c1e',
    messagingSenderId: '74105196603',
    projectId: 'super-pet-connect',
    authDomain: 'super-pet-connect.firebaseapp.com',
    storageBucket: 'super-pet-connect.firebasestorage.app',
    measurementId: 'G-EJQFMRXRDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5syzViSsPEWnqp8u-FluqR8m8fTWhSAg',
    appId: '1:74105196603:android:6d48db6846a48a9e4e0c1e',
    messagingSenderId: '74105196603',
    projectId: 'super-pet-connect',
    storageBucket: 'super-pet-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj49_O8O91PpJENOpCAxmo00qP0BCxra4',
    appId: '1:74105196603:ios:23bb64068915e8f74e0c1e',
    messagingSenderId: '74105196603',
    projectId: 'super-pet-connect',
    storageBucket: 'super-pet-connect.firebasestorage.app',
    iosBundleId: 'com.choonok.superpetconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj49_O8O91PpJENOpCAxmo00qP0BCxra4',
    appId: '1:74105196603:ios:23bb64068915e8f74e0c1e',
    messagingSenderId: '74105196603',
    projectId: 'super-pet-connect',
    storageBucket: 'super-pet-connect.firebasestorage.app',
    iosBundleId: 'com.choonok.superpetconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdO-LjFNK3TDE0C0UfivNCe4_Xs-CVGj8',
    appId: '1:74105196603:web:0f7d19c56f42229d4e0c1e',
    messagingSenderId: '74105196603',
    projectId: 'super-pet-connect',
    authDomain: 'super-pet-connect.firebaseapp.com',
    storageBucket: 'super-pet-connect.firebasestorage.app',
    measurementId: 'G-EJQFMRXRDF',
  );
}
