// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk2QQsumZYhF79NRoDWBUrC760uupe88I',
    appId: '1:492440933290:web:1315c9df46bd7e948411d3',
    messagingSenderId: '492440933290',
    projectId: 'super-pet-connect-ibdp',
    authDomain: 'super-pet-connect-ibdp.firebaseapp.com',
    storageBucket: 'super-pet-connect-ibdp.firebasestorage.app',
    measurementId: 'G-Q58BSQWSXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoAtZCRQBE5PQYJfe6-4QzVng7afbhXnM',
    appId: '1:492440933290:android:dba4e1ca3949ec3b8411d3',
    messagingSenderId: '492440933290',
    projectId: 'super-pet-connect-ibdp',
    storageBucket: 'super-pet-connect-ibdp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmdXPM4JGHiIInkj3-gJ503dh8csByFDI',
    appId: '1:492440933290:ios:cc6fd8836020ca2c8411d3',
    messagingSenderId: '492440933290',
    projectId: 'super-pet-connect-ibdp',
    storageBucket: 'super-pet-connect-ibdp.firebasestorage.app',
    iosBundleId: 'com.example.superpet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmdXPM4JGHiIInkj3-gJ503dh8csByFDI',
    appId: '1:492440933290:ios:cc6fd8836020ca2c8411d3',
    messagingSenderId: '492440933290',
    projectId: 'super-pet-connect-ibdp',
    storageBucket: 'super-pet-connect-ibdp.firebasestorage.app',
    iosBundleId: 'com.example.superpet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk2QQsumZYhF79NRoDWBUrC760uupe88I',
    appId: '1:492440933290:web:0335733df0bdcedb8411d3',
    messagingSenderId: '492440933290',
    projectId: 'super-pet-connect-ibdp',
    authDomain: 'super-pet-connect-ibdp.firebaseapp.com',
    storageBucket: 'super-pet-connect-ibdp.firebasestorage.app',
    measurementId: 'G-S9EKPM82DQ',
  );
}
